# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: normal
  JOBS_NUMBER: 8

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-18.04"
    mac:
      imageName: "macos-10.13"
    windows:
      imageName: "vs2017-win2016"
  maxParallel: 3

pool:
  vmImage: $(imageName)
  
steps:
- bash: |
    mkdir build
    cd build
    cmake ..
    cmake --build . -j  $JOBS_NUMBER
  displayName: 'Build project'
